----- Users Creation -----

-- Creation of App Store Admin

CREATE USER STORE_ADMIN IDENTIFIED BY QueryNinjas#6210;


-- Creation of Developer Manager

CREATE USER DEVELOPER_MANAGER IDENTIFIED BY QueryNinjas#6210;


-- Creation of USER_MANAGER

CREATE USER USER_MANAGER IDENTIFIED BY QueryNinjas#6210;




----- Access Grants for the created users -----

GRANT CONNECT, RESOURCE TO STORE_ADMIN;
GRANT CONNECT, RESOURCE TO DEVELOPER_MANAGER;
GRANT CONNECT, RESOURCE TO USER_MANAGER;





----- Quota for the created users -----

ALTER USER STORE_ADMIN QUOTA UNLIMITED ON DATA;
ALTER USER DEVELOPER_MANAGER QUOTA UNLIMITED ON DATA;
ALTER USER USER_MANAGER QUOTA UNLIMITED ON DATA;




----- Granting Access for the created users -----


-- Granting accesses for TABLES to STORE_ADMIN user

GRANT SELECT, INSERT, UPDATE, DELETE ON ADVERTISEMENT TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_CATEGORY TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON APPLICATION TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PINCODE TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROFILE TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REVIEWS TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON SUBSCRIPTION TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_APP_CATALOGUE TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_INFO TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEVELOPER TO STORE_ADMIN;

-- Granting accesses for Views to STORE_ADMIN user

GRANT CREATE VIEW TO STORE_ADMIN;


-- Granting accesses for Stores Procedures to STORE_ADMIN user

GRANT CREATE SESSION,CREATE TABLE,CREATE PROCEDURE TO STORE_ADMIN;



-- Granting access for TABLES to DEVELOPER_MANAGER user
    
GRANT SELECT ON REVIEWS TO DEVELOPER_MANAGER;
GRANT SELECT ON APP_CATEGORY TO DEVELOPER_MANAGER;

GRANT SELECT, INSERT, UPDATE ON APPLICATION TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON ADVERTISEMENT TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON SUBSCRIPTION TO STORE_ADMIN;


-- Granting access for TABLES to USER_MANAGER user

GRANT SELECT ON USER_APP_CATALOGUE TO USER_MANAGER;
GRANT SELECT ON SUBSCRIPTION TO USER_MANAGER;

GRANT SELECT, INSERT, UPDATE ON USER_INFO TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON PAYMENTS TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON PINCODE TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON PROFILE TO STORE_ADMIN;
GRANT SELECT, INSERT, UPDATE ON REVIEWS TO STORE_ADMIN;

